version: '3.8'
services:
  app:
    build: .
    volumes:
      - /home/snek/repos/random_crap/stocks:/usr/src/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
